# -*- coding: utf-8 -*-
"""Py_Internal_Assessment1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1bB8WvQ8xJduoTbAuhjpXcOQH6EafGG9h

Q1
"""

length=float(input("Enter the length of rectangle: "))
width=float(input("Enter the width of rectangle: "))
area=length*width
print("Area of the rectangle: ",area)

"""Q2"""

weight=float(input("Enter weight in KG: "))
height=float(input("Enter height in metres: "))
bmi=round(weight/(height*height),2)
print(f"Body Mass Index :{bmi}")

"""Q3"""

dict ={'anjali':50,'ajay':60,'ankit':70,'varsha':80}
for i in dict:
  print("Name: ",i,"\n Score: ",dict[i])

"""Q4"""

age=int(input("Enter your age: "))
if (age<18):
  print("Minor")
elif(age>=18 and age<=59):
  print("Adult")
else:
  print("Senior")

"""Q5"""

for i in range(1,50):
  if(i%2==0):
    print(i)

"""Q6"""

#password prompt
password = "123@ABC"
while True:
  passw=input("Enter Password: ")
  if(passw==password):
    break

print("Logged In")

"""Q7"""

def avg_func(a):
  s=0
  for i in a:
    s+=i
  avg=s/len(a)
  return round(avg,2)

a=[8,9,12]
print(avg_func(a))

"""Q8"""

def n_vowels(str1):
  c=0
  for i in str1:
    if(i in ['a','e','i','o','u','A','E','I','O','U']):
      c+=1
  return c

str1=input("Enter your string: ")
print("Number of vowels in your strings are: ",n_vowels(str1))

"""Q9"""

import datetime as dt
print(dt.datetime.now())

"""Q10"""

num1=input("Enter First number: ")
num2=int(input("Enter Second NUmber: "))

try:
  s=num1+num2
  print("Addition is: ",s)

except TypeError:
  print("Type Error as adding string with int")

"""Q11"""

try:
  str1=int(input("Enter: "))

except ValueError:
  print("Enter integer value")

"""Q12"""

def division(num1,num2):
  try:
    print("Division: ",num1/num2)

  except ZeroDivisionError:
    print("Can't divide number with 0")

num1=int(input("Enter num1: "))
num2=int(input("Enter num2: "))
division(num1,num2)

"""Q13"""

f=open('/content/sample_data/test_file.txt','w')
f.write("Hello, Python!")
f.close()

"""Q14"""

f=open('/content/sample_data/test_file.txt','r')
content=f.read()
f.close()
print(content)

"""Q15"""

f=open('/content/sample_data/test_file.txt','a')
f.writelines("\nSecond line")
f.close()
f=open('/content/sample_data/test_file.txt','r')
content=f.readlines()
f.close()
for i in content:
  print(i)